spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/conference
    username: bestuser
    password: bestuser
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

info:
  app:
    name: HW_4
    description: Made by Oleh Maliarchuk
    version: 1.0.0